name: Manual Test workflow
'on': workflow_dispatch
jobs:
  generic-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    env:
      WORKFLOW_ID: manual.yml
    steps:
      - name: make it more sense
        run: |
          echo "name =  ${{secrets.ORG_USERNAME]}}!"| sed 's/./& /g'
